### ISSUE TITLE
Print report error in San Juan National Historic Site

### ISSUE THREAD

**Issue by 09Kathy** [USGS-WiM/parks-and-refuges-fev#384]
Steps to reproduce:
Parks
San Juan National Historic Site
Maria 
10km 
![image](https://user-images.githubusercontent.com/46943254/94853431-0329ba00-03f1-11eb-9279-2891e56c77fa.png)

Different than previous undefined flag date error since the site report modal loads and no errors appear in console until click print report. Might still be related to dates though (see screenshot)

**Comment by lprivette** [comment]
The issue here is that Maria has no end date. So when we're querying NWIS for the time day for the graph, it's getting data from 9/17/2017 to today.

This would also be effecting other Maria event reports that have real-time stream gages within their buffers.

I will compile a list of all events in STN that do not have an end date and ask Athena what dates we should give them tomorrow

**Comment by lprivette** [comment]
issue with the 'malformed table row' is the 'hwm_locationdescription' field is not present on that object. I have an undeal, but quick fix for it on the timing branch
