### ISSUE TITLE
Ford's Theatre National Historic Site freezes app

### ISSUE THREAD

**Issue by 09Kathy** [USGS-WiM/parks-and-refuges-fev#428]
Ford's Theatre National Historic Site (NPS) results in an endless loader (with both Explore Map and Generate Report), both locally and on the test site. No related console errors. I looked at the data in the jump drive and didn't see anything suspicious (2 part polygon, no topology errors). 

Even if we do solve this specific site, might be good to put in a catch for when the loader takes too long and redirect user back to the welcome modal or something in case there are more like this.

**Comment by lprivette** [comment]
Dang yeah this is happening for me as well.

Seems to be something with that site. if you test the query that's getting ran in the network tab the server states "Unable to complete operation". I switched the format to html for readability. You switch it back to "f=json" at the end of the url to see the 400 error. https://gis.wim.usgs.gov/arcgis/rest/services/DOIFEV/DOI_FEV/MapServer/1/query?returnGeometry=true&where=UNIT_NAME%3D%27Ford%27s%20Theatre%20National%20Historic%20Site%27&outSr=4326&outFields=*&inSr=4326&geometry=%7B%22xmin%22%3A-90%2C%22ymin%22%3A31.952162238024975%2C%22xmax%22%3A-84.375%2C%22ymax%22%3A36.59788913307022%2C%22spatialReference%22%3A%7B%22wkid%22%3A4326%7D%7D&geometryType=esriGeometryEnvelope&spatialRel=esriSpatialRelIntersects&geometryPrecision=4&maxAllowableOffset=0.025666065705128204&callback=window._EsriLeafletCallbacks.c43&f=html

and here's an example of a working one: 
https://gis.wim.usgs.gov/arcgis/rest/services/DOIFEV/DOI_FEV/MapServer/1/query?returnGeometry=true&where=UNIT_NAME%3D%27American%20Memorial%20Park%27&outSr=4326&outFields=*&inSr=4326&geometry=%7B%22xmin%22%3A145.546875%2C%22ymin%22%3A15.284185114076433%2C%22xmax%22%3A146.25%2C%22ymax%22%3A15.961329081596647%2C%22spatialReference%22%3A%7B%22wkid%22%3A4326%7D%7D&geometryType=esriGeometryEnvelope&spatialRel=esriSpatialRelIntersects&geometryPrecision=4&maxAllowableOffset=0.0032082582131410255&callback=window._EsriLeafletCallbacks.c16&f=html

I think we might be able to use an error parameter to catch that 500 but I could also be wrong.
![image](https://user-images.githubusercontent.com/23640741/111559121-55278780-8766-11eb-96cc-139fdbed32a1.png)
I also can't run gulp because I installed WSL and for some reason that has messed up my normal workflow with existing projects and using git bash. So i'll finish figuring this out tomorrow.

**Comment by 09Kathy** [comment]
None of the sites with an apostrophe work. I'll try removing those when comparing the text matching

**Comment by lprivette** [comment]
good catch, yeah i bet that's causing it
