### ISSUE TITLE
Hide interest boundaries & buffers

### ISSUE THREAD

**Issue by kathymd** [USGS-WiM/parks-and-refuges-fev#70]
If you search for a refuge three times in a row, the interest boundaries appear. They should stay hidden whenever there is an approved boundary.

**Comment by 09Kathy** [comment]
- [ ] Clear buffers from previous search: 
![image](https://user-images.githubusercontent.com/46943254/81979918-59898e00-95f3-11ea-90a9-076271849353.png)

**Comment by 09Kathy** [comment]
The interest boundaries will stay hidden if I increase the timeout to 20 seconds, which makes it seem like the map has frozen after running an FWS search. The refuges were originally added to the search modals because they wanted us to search interest boundaries when the search didn't match an approved boundary. However, there are few to no cases like this that exist (every polygon interest boundary I've found that doesn't have a corresponding approved boundary is not searchable in our USGS search api). @lprivette , what do you think about removing them from the search?

**Comment by lprivette** [comment]
I'll remove it on my currenty branch. We won't be using the search api anymore for park/refuge identification we'll be populating a list directly from the services

I will remove that second layer they asked us query if a search didn't match. If they actually find one case of it like that we can add it in as a separate land type > list of refuges
